### ISSUE TITLE
duplicated class in MiP and MiPosaur frameworks

### ISSUE THREAD

**Issue by samyusk** [WowWeeLabs/MiPosaur-iOS-SDK#3]
Hi, 

We developed an iOS app to use MiP framework to control MiP robot some time ago. We're updating our app to use MiPosaur framework to control MiPosaur robot now. After linking with the MiPosaur framework, the XCode's console shows following warning messages when our app starts to run

objc[6280]: Class X is implemented in both /../Frameworks/WowWeeMiPosaurSDK.framework/WowWeeMiPosaurSDK and /../Frameworks/WowWeeMiPSDK.framework/WowWeeMiPSDK. One of the two will be used. Which one is undefined.
...
above X are 
BRPortTimedEvent
BRRSSIReportService
BRProgrammableIOService
BluetoothRobotFinder
BRBaseService
BRAdcInputService
RobotCommand
BRDeviceInformationService
BRPortTimedIOEvent
YMSCBDescriptor
YMSCBCentralManager
BRPortTimedEventService
BRModuleParametersService
BluetoothRobot
BRTimingTurnoverOutputService
YMSCBStoredPeripherals
BRReceiveDataService
BRPortTimedPWMEvent
YMSCBUtils
BRAntiHijackingService
YMSCBService
BRBatteryLevelService
YMSCBCharacteristic
BRSendDataService
BRPwmOutputService
YMSCBPeripheral
MSWeakTimer
DDLog
DDLoggerNode
DDLogMessage
DDAbstractLogger
DDASLLogCapture
DDContextWhitelistFilterLogFormatter
DDContextBlacklistFilterLogFormatter
DDLoggingContextSet
DDDispatchQueueLogFormatter
DDLogFileManagerDefault
DDLogFileFormatterDefault
DDFileLogger
DDLogFileInfo
DDTTYLogger
DDTTYLoggerColorProfile
DDMultiFormatter
DDAbstractDatabaseLogger
DDASLLogger

Our questions are:
1. Is it OK one iOS app links to both MiP and MiPosaur frameworks? We're afraid not since at least the header file for the BluetoothRobot is not identical.
2. Any suggestion to solve above warning?
3. Any plan to release  one framework to support both MiP and MiPosaur?

Thanks

**Comment by ffchan** [comment]
Hi Sam,
Please use the MiPSDK for your project, the MiPSDK ( https://github.com/WowWeeLabs/MiP-iOS-SDK ) have included MiPosaur classes now.
